<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByIdOrName($category){
		$res = $this->createQueryBuilder('c')
                    ->where("c.id = :category")
                    ->orWhere("c.name = :category");
        
        $res->setParameter('category', $category)->setMaxResults(1);

        return $res->getQuery()->getOneOrNullResult();
	}
}
