<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByCategory(Category $category, int $page, int $nbItems)
    {
        $qb = $this->createQueryBuilder("p");
        $qb->innerJoin('p.categories', 'c')
           ->where("c.id = :categoryId")
           ->setParameter("categoryId", $category->getId())
           ->setFirstResult($nbItems * ($page - 1))
           ->setMaxResults($nbItems);
        
        return $qb->getQuery()->getResult();
    }
}
