# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    product_service:
        class: AppBundle\Services\ProductService
        public: true
        autowire: false
        arguments: [ '@doctrine.orm.entity_manager']

    auth_token_user_provider:
        class: AppBundle\Security\AuthTokenUserProvider
        arguments: ["@auth_token_repository", "@user_repository"]
        public:    false

    auth_token_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["AppBundle:AuthToken"]

    user_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["AppBundle:User"]

    auth_token_authenticator:
        class:     AppBundle\Security\AuthTokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false

    #app.category_listener:
    #        class: AppBundle\Listener\CategoryListener
    #        arguments: ["2018-04-25"]
    #        tags:
    #           - { name: kernel.event_listener, event: kernel.response, method: processCatg }

    #app.category_subscriber:
    #        class:     AppBundle\Subscriber\CategorySubscriber
    #        tags:
    #            - { name: kernel.event_subscriber }

    #app.censorship_processor:
    #    class:     AppBundle\Bigbrother\CensorshipProcessor
    #    arguments: ["@mailer"]

    #app.censorship_listener:
    #    class:     AppBundle\Bigbrother\CensorshipListener
    #    arguments: ["@app.censorship_processor", [1, 2, 3]]
    #    tags:
    #        - { name: kernel.event_listener, event: app.bigbrother.post_message, method: processMessage }

    app.security.login_form_authenticator:
            class: AppBundle\Security\LoginFormAuthenticator
            autowire: true

    app.doctrine.hash_password_listener:
            class: AppBundle\Doctrine\HashPasswordListener
            autowire: true
            tags:
                - { name: doctrine.event_subscriber }
